project_id = "ychnmaaximnoxvwnzrgs"

[functions.setup]
verify_jwt = false

[functions.confirm-device]
verify_jwt = false

[functions.device-api]
verify_jwt = false

[functions.notification-system]
verify_jwt = true
